# Generated by Django 3.2.25 on 2026-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_and_sauna_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
    ]
