# Generated by Django 3.2.25 on 2026-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_and_sauna_app', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='special_menu',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
