# Generated by Django 3.2.25 on 2026-03-23 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_and_sauna_app', '0003_auto_20260322_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sweet_and_sauna_app.product'),
        ),
        migrations.AlterField(
            model_name='product_discount',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sweet_and_sauna_app.discount'),
        ),
    ]
