# Generated by Django 3.2.25 on 2026-03-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_and_sauna_app', '0004_auto_20260323_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_menu',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1),
        ),
    ]
