# Generated by Django 3.2.25 on 2026-03-27 12:07

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('sweet_and_sauna_app', '0006_product_tag_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
